name: Ansible Role Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Value from the version i.e 4.26.0"
        type: string
        required: true
      dry_run: 
        description: 'Flag to indicate if the workflow is triggered to create a dry-run release'
        required: true
        type: boolean
        default: false
      dry_run_release_url: 
        description: 'URL of the dry-run release'
        required: false
        type: string
  workflow_call:
    inputs:
      version:
        description: "Value from the version i.e 4.26.0"
        type: string
        required: true
      dry_run: 
        description: 'Flag to indicate if the workflow is triggered to create a dry-run release'
        required: true
        type: boolean
        default: false
      dry_run_release_url: 
        description: 'URL of the dry-run release'
        required: false
        type: string

permissions:
  contents: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      LIQUIBASE_VERSION: ${{ inputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: liquibase/liquibase-ansible
          token: ${{ secrets.BOT_TOKEN }}

      - name: Configure Git
        run: |
          git config --local user.email "64099989+liquibot@users.noreply.github.com"
          git config --local user.name "liquibot"

      - name: Update main.yml
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          sed -i "s/liquibase_ver: .*/liquibase_ver: ${{ inputs.version }}/" defaults/main.yml
          wget --header="Authorization: token ${{ secrets.BOT_TOKEN }}" -O liquibase-${{ inputs.version }}.tar.gz ${{ inputs.dry_run_release_url}}/liquibase-${{ inputs.version }}.tar.gz
          sha256=$(sha256sum liquibase-${{ inputs.version }}.tar.gz | awk '{ print $1 }')
          echo "SHA256: $sha256"
          echo "  '${{ inputs.version }}': sha256:$sha256" >> defaults/main.yml
          cat defaults/main.yml
          git add defaults/main.yml
          # Check if there are changes before committing
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
          else
            git commit -m "Update liquibase.version to ${{ inputs.version }}"
            git remote set-url origin https://liquibot:${{ secrets.BOT_TOKEN }}@github.com/liquibase/liquibase-ansible.git
            if [[ "${{ inputs.dry_run }}" == false ]]; then
              git push
            else
                echo "Dry run mode: changes have not been pushed."
            fi
          fi

      - name: Ansible import
        if: ${{ inputs.dry_run == false }}
        run: |
          ansible-galaxy role import --token ${{ secrets.ANSIBLE_TOKEN }} --branch main --role-name liquibase liquibase liquibase-ansible
